version: '3.7'
services:
  rover:
    image: aztfmod/rover:0.15.4-2105.2603
    user: vscode

    labels:
      - "caf=Azure CAF"

    volumes:
      - ..:/tf/caf
      - volume-caf-vscode:/home/vscode
      - ~/.ssh:/tmp/.ssh-localhost:ro
      - volume-caf-vscode-bashhistory:/commandhistory
      - /var/run/docker.sock:/var/run/docker.sock

    command: /bin/bash -c "while sleep 1000; do :; done"

volumes:
  volume-caf-vscode:
    labels:
      - "caf=Azure CAF"
  volume-caf-vscode-bashhistory: